// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLKulk9yiyhy6P7_d5tNSeV837CVmlUBA',
    appId: '1:551431577143:web:f2076da383e738f37669b2',
    messagingSenderId: '551431577143',
    projectId: 'toilet-info',
    authDomain: 'toilet-info.firebaseapp.com',
    databaseURL: 'https://toilet-info-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'toilet-info.appspot.com',
    measurementId: 'G-2KV81Y0G91',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe9Fdxa2hWD6_Dfd4cFSKQGPt-6S3j_xY',
    appId: '1:551431577143:android:314e39a6c81bc74d7669b2',
    messagingSenderId: '551431577143',
    projectId: 'toilet-info',
    databaseURL: 'https://toilet-info-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'toilet-info.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw_HIIX23VppjgRlWsaOUfULgeCGIWUg8',
    appId: '1:551431577143:ios:57829f77c77c27257669b2',
    messagingSenderId: '551431577143',
    projectId: 'toilet-info',
    databaseURL: 'https://toilet-info-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'toilet-info.appspot.com',
    androidClientId: '551431577143-e9r938ekis1s4fvk21svnqa6jg9fnn0v.apps.googleusercontent.com',
    iosClientId: '551431577143-nqhd86rp2r3a2tuu51pvicddp8j8b0f5.apps.googleusercontent.com',
    iosBundleId: 'com.huudan.toiletclient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw_HIIX23VppjgRlWsaOUfULgeCGIWUg8',
    appId: '1:551431577143:ios:fcbb49d50abc413f7669b2',
    messagingSenderId: '551431577143',
    projectId: 'toilet-info',
    databaseURL: 'https://toilet-info-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'toilet-info.appspot.com',
    androidClientId: '551431577143-e9r938ekis1s4fvk21svnqa6jg9fnn0v.apps.googleusercontent.com',
    iosClientId: '551431577143-uq0bsb06flfe5j09ne8a9lpuup3etknp.apps.googleusercontent.com',
    iosBundleId: 'com.example.toiletClient.RunnerTests',
  );
}
